osx_image: xcode7.3

sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: linux
      env:
        - CC=clang
        - CXX=clang++
        - npm_config_clang=1
        - LLVM_VERSION=3.7.0
        - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
        - CXX=$HOME/clang-$LLVM_VERSION/bin/clang++
        - CPPFLAGS="-I $HOME/clang-$LLVM_VERSION/include/c++/v1"
        - CXXFLAGS=-lc++
        - DISPLAY=":99.0"
        - LD_LIBRARY_PATH=$HOME/clang-$LLVM_VERSION/lib:$LD_LIBRARY_PATH
      before_install:
        - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
        - mkdir $HOME/clang-$LLVM_VERSION
        - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang-$LLVM_VERSION --strip-components 1
        - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      compiler: clang
    - os: osx

cache:
  directories:
  - node_modules
  - $HOME/.electron

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - xvfb
      - icnsutils
      - graphicsmagick
      - xz-utils

install:
  - nvm install 6
  - npm i

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run coverage-lcovonly; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run test; fi

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi

deploy:
  provider: script
  script: npm run build-release && npm run dist
  skip_cleanup: true
  on:
    branch: master
