version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules -> npm-shrinkwrap.json
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 5 x64
  - git reset --hard HEAD
  - npm install

build: off

test_script: npm run test

deploy_script:
  - ps: >-
      if($env:appveyor_repo_branch -eq 'master') {
        (npm run build-release) -and (npm run dist)
      }
